name: FE Auto Build & Push

on:
  push:
    branches: ["main"]
    paths:
      - "frontend-user/**"
      - "frontend-admin/**"
      - ".github/workflows/fe-deploy.yml"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # =============================
      # LOGIN DOCKER HUB (BẮT BUỘC)
      # =============================
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # =============================
      # Build & Push FE USER
      # =============================
      - name: Build & Push FE User
        uses: docker/build-push-action@v4
        with:
          context: ./frontend-user
          push: true
          tags: datdevv/frontend-user:latest

      # =============================
      # Build & Push FE ADMIN
      # =============================
      - name: Build & Push FE Admin
        uses: docker/build-push-action@v4
        with:
          context: ./frontend-admin
          push: true
          tags: datdevv/admin-frontend:latest
