name: FE Build & Push

on:
  push:
    branches: ["main"]
    paths:
      - "frontend-user/**"
      - "frontend-admin/**"
      - ".github/workflows/fe-build-push.yml"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: docker

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push FE User
        uses: docker/build-push-action@v4
        with:
          context: ./frontend-user
          push: true
          tags: datdevv/frontend-user:latest

      - name: Build & Push FE Admin
        uses: docker/build-push-action@v4
        with:
          context: ./frontend-admin
          push: true
          tags: datdevv/admin-frontend:latest
