name: FE Build & Push

on:
  push:
    branches: ["main"]
    paths:
      - "frontend-user/**"
      - "frontend-admin/**"
      - ".github/workflows/fe-deloy.yml"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: docker

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # =============================
      # Build & Push Frontend User
      # =============================
      - name: Build FE User
        uses: docker/build-push-action@v4
        with:
          context: ./frontend-user
          file: ./frontend-user/Dockerfile
          push: true
          tags: datdevv/frontend-user:latest

      # =============================
      # Build & Push Frontend Admin
      # =============================
      - name: Build FE Admin
        uses: docker/build-push-action@v4
        with:
          context: ./frontend-admin
          file: ./frontend-admin/Dockerfile
          push: true
          tags: datdevv/admin-frontend:latest
